language: swift
osx_image: xcode10.2

before_install:
  - rvm use $RVM_RUBY_VERSION

install: 
  - bundle install --without=documentation --path ../travis_bundle_dir

    
script:
    - xcodebuild test -scheme CodableSaveLoad -workspace CodableSaveLoad.xcworkspace -destination 'platform=iOS Simulator,name=iPhone SE'  | xcpretty
    - slather coverage -s --scheme CodableSaveLoad --workspace CodableSaveLoad.xcworkspace CodableSaveLoad.xcodeproj

after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode


    
