language: swift
osx_image: xcode10.2

before_install:
  - rvm use $RVM_RUBY_VERSION
  - bundle config --local build.nokogiri --use-system-libraries

install: 
  - bundle install --without=documentation --path ../travis_bundle_dir

    
script:
    - swift build
    - xcodebuild test -scheme CodableSaveLoad -destination 'platform=iOS Simulator,name=iPhone SE'  | xcpretty
    - bundle exec slather coverage -s --scheme CodableSaveLoad CodableSaveLoad.xcodeproj

after_success: 
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode
